### PR TITLE
exposing search_gateway_from function

### PR DESCRIPTION
**Pull request by vinipsmaker**

### CODE REVIEW

**Comment by vinipsmaker** [comment]
With this change, I can finally make use of `rust-igd` to add UPnP IGD port forwarding support within the [SAFEnetwork's crust library](https://github.com/vinipsmaker/crust/commit/2c26db4a26b5e503da718ccc04f63d462ebe1699).

**Comment by vinipsmaker** [comment]
Please, bump the version once this pull request is merged, then I can change the [Cargo.toml file](https://github.com/vinipsmaker/crust/commit/2c26db4a26b5e503da718ccc04f63d462ebe1699#diff-80398c5faae3c069e4e6aa2ed11b28c0R23) to use the upstream library.

**Comment by SBSTP** [comment]
Done. Thanks again!

**Comment by vinipsmaker** [comment]
Thanks for being such a responsive maintainer. It surely helped a lot. :)

Way different from the months of interaction with the kbd maintainer until I got my Brazilian keyboard layout two-lines patch accepted (but still no new version released).

**Comment by SBSTP** [comment]
No problem, I'm super happy someone is using this. I wasn't updating it since I don't currently use it. But since there's interest, I am now. Also, if your patch gets into crust, it's probably going to bring a lot more users. I'm down for that!

**Pull request merged**
