### PR TITLE
Use agonistic IP parsing & Manual Tokio selection

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
Should solve #52 and #47?

### CODE REVIEW

**Comment by darrinsmart** [comment]
I tried to test this with the aio example, but it didn't compile for me (OSX Big Sur). Failed at igd.

Is there something I'm doing wrong?

Partial output of : `cargo run --features=aio --example aio 10.1.1.35:4321`


```
   Compiling tokio v1.0.1
...
   Compiling igd v0.12.0 (/Users/darrin/src/t/rust-igd)
error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
 --> src/aio/search.rs:6:5
  |
6 | use tokio::net::UdpSocket;
  |     ^^^^^ use of undeclared crate or module `tokio`

```

**Comment by sbstp** [comment]
Hey thanks for this. Looks like I misconfigured the CI, it was not running for pull requests. Can you push again to trigger it?

**Comment by vorot93** [comment]
Tokio 0.2 and especially 0.3 are obsolete at this point, there's little sense in providing support for them.

**Comment by stevefan1999-personal** [comment]
@vorot93 well I used this project in actix and 3.x is still using tokio 0.2 this point...maybe i misconfigured something?

**Comment by Silvea12** [comment]
@stevefan1999-personal Hey, this issue is a blocker for me too, as I need support for dual-stack LAN. If needed, I can take over this PR.
I can also just make my own if you'd prefer (still based off yours, yours has good work that doesn't need to be duplicated)

**Comment by canewsin** [comment]
@Silvea12 You still interested

**Comment by Silvea12** [comment]
@canewsin I jumped over to use [rupnp](https://lib.rs/crates/rupnp) for what I was doing instead, though I am no longer really touching this anymore, and it's been long enough I don't remember what changes I planned to make unfortunately.

It generally looks like this crate isn't maintained anymore (last commit 17 months ago) so if I were you I'd either fork it or look elsewhere like I did.

A bit of sample code for IGD stuff in rupnp:
```rs
async fn get_igd() -> Result<(Device, Service)> {
    trace!("Discovering root node");
    let discovered_devices =
        rupnp::discover(&SearchTarget::RootDevice, Duration::from_millis(5000))
            .await?
            .filter_map(|e| e.ok());
    pin!(discovered_devices);

    let root_device: Device = discovered_devices
        .next()
        .await
        .ok_or_else(|| eyre!("No root device found, maybe UPnP is disabled?"))?;

    trace!(url = %root_device.url());

    for service in root_device.services_iter() {
        trace!(service_type = %service.service_type(), service_id = service.service_id());
    }

    trace!(device = root_device.friendly_name(), "Discovering services");
    let service = root_device
        .services_iter()
        .find(|service| {
            let urn = service.service_type();
            urn.domain_name() == "schemas-upnp-org"
                && urn.typ() == "WANIPConnection"
                && urn.version() <= 2
        })
        .cloned()
        .ok_or_else(|| eyre!("IGD not supported on your router."))?;

    Ok((root_device, service))
}
```

**Pull request closed without merging**
