### PR TITLE
Port mapping functions

### PR DESCRIPTION
**Pull request by vinipsmaker**

### CODE REVIEW

**Comment by SBSTP** [comment]
I just tried it! Works well, thanks. I'm going to merge this soon, I'm working on switching the http stuff to hyper. I'm also thinking that those should be methods of the Gateway object, now that it exists (also get_external_ip). What do you think?

**Comment by vinipsmaker** [comment]
> I'm working on switching the http stuff to hyper.

To be honest, I don't really care. I care more about proper XML parsing.

> I'm also thinking that those should be methods of the Gateway object, now that it exists

Care to elaborate?

**Comment by SBSTP** [comment]
> To be honest, I don't really care. I care more about proper XML parsing.

I want to remove the dependency on libcurl and libssl.

> Care to elaborate?

Well, I think search_gateway should return a Gateway object.  The `get_external_ip, 'add_port', 'remote_port' functions should be methods, instead of the current procedural/C style.

**Comment by vinipsmaker** [comment]
> I want to remove the dependency on libcurl and libssl.

I'm not sure why remove the libcurl dependency, but makes sense to get rid of SSL-related stuff.

> Well, I think search_gateway should return a Gateway object. The `get_external_ip, 'add_port', 'remote_port' functions should be methods, instead of the current procedural/C style.

Good idea. I support it.

**Comment by SBSTP** [comment]
I think it's easier for windows users, they don't have to install libcurl.

**Comment by vinipsmaker** [comment]
> I think it's easier for windows users, they don't have to install libcurl.

It makes sense. Not sure if hyper is gonna take over HTTP clients within the rust community. The one thing I could say for sure: Async support within Rust is weak and needs improvements.

**Comment by SBSTP** [comment]
I also dropped `regex_macros`, because it hasn't been updated in a while and Regex::new is the preferred alternative for now.

**Comment by vinipsmaker** [comment]
> I also dropped regex_macros, because it hasn't been updated in a while and Regex::new is the preferred alternative for now.

I noticed and I didn't like. The `regex!` macro did compile-time magic and freed us from have to `unwrap` the regex. The more errors you move to compile-time, the better.

**Comment by SBSTP** [comment]
[This](http://www.reddit.com/r/rust/comments/3b2i0f/psa_regex_is_now_slower_than_regexnew/) is the post about it. `regex!` is not broken, but it's a bit in a bad state atm. I will use `regex!` again when they fix the various issues.

**Pull request merged**
