### PR TITLE
add function to let the user to choose network interface to be used

### PR DESCRIPTION
**Pull request by vinipsmaker**
This is also useful if the user can do without google.ca.

### CODE REVIEW

**Comment by SBSTP** [comment]
Thank you! You've made me realize how stupid I was! I [created a branch](https://github.com/SBSTP/rust-igd/commits/issue-6) with your changes and changes from me, let me know what you think. What I wanted to do all along was listen on any interface... I realize now that it's the 0.0.0.0 address.

**Comment by SBSTP** [comment]
Also I don't think you need to specify both the address and the port, right? I can change the function to take only an `Ipv4Addr` and not a full `SocketAddrV4`.

**Comment by vinipsmaker** [comment]
I liked your changes It'd be fine for me.

**Comment by SBSTP** [comment]
I wrote the changes and published it on crates.io.

**Pull request merged**
